#!/bin/sh -e
clear
EMSDK_QUIET=1
source "/home/andrew/git/emsdk/emsdk_env.sh"
[[ ! -d ../build ]] && mkdir ../build
#emcc -o index.html main.cpp -Os -Wall ./raylib/libraylib.a -I. -L. -L./raylib -s USE_GLFW=3 --shell-file shell.html -DPLATFORM_WEB
PLATFORM="PLATFORM_DESKTOP"
CC="g++ -pipe"
CFLAGS="-Os -w -I. -I./include"
LIBS="-lraylib"
echo "Linux"
echo "###############################"
$CC $CFLAGS -o ../build/retro-heroes main.cpp game.cpp $LIBS -D$PLATFORM # linux
CC="x86_64-w64-mingw32-g++ -pipe"
CFLAGS="-Os -w -I/usr/x86_64-w64-mingw32/include -I. -I./include -static-libgcc -static-libstdc++ -static -ggdb"
LIBS="-L. -L./lib -lraylib -lopengl32 -lgdi32 -lwinmm"
echo "Windows"
echo "###############################"
$CC $CFLAGS -o ../build/retro-heroes.exe main.cpp game.cpp $LIBS -D$PLATFORM # windows
PLATFORM="PLATFORM_WEB"
CC="emcc -pipe"
CFLAGS="-Os -w ./raylib/libraylib.a -I. -I./include -ggdb"
LIBS="-L. -L./raylib -s USE_GLFW=3"
PAGE="--shell-file shell.html"
echo "Web"
echo "###############################"
$CC -o ../build/index.html main.cpp game.cpp $CFLAGS $LIBS $PAGE -D$PLATFORM # web
